name: 'Workflow Dispatch'
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    name: 'Lint'
    uses: ./.github/workflows/lint.yml

  call-build:
    name: 'Build'
    needs: call-lint
    uses: ./.github/workflows/build.yml

# ToDo: Uncomment this flow when tests will be ready/refactored
#  call-test:
#    name: 'Test'
#    needs: call-build
#    uses: ./.github/workflows/test.yml
