name: 'Lint'
on: workflow_call
defaults:
  run:
    shell: bash

jobs:
  super-lint:
    name: "Super Linter"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to fetch version

      - name: Run Super Linter
        uses: github/super-linter/slim@v4
        env:
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: WARN
          VALIDATE_ALL_CODEBASE: true
          MULTI_STATUS: true

          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          DOCKERFILE_HADOLINT_FILE_NAME: '../linters/.hadolint.yml'
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_OPENAPI: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: "../../.eslint.json"
